#!/bin/sh
if ! command -v java >/dev/null 2>&1; then
    echo "java not found"
    exit 1
fi

if [ ! -f /usr/share/tlauncher/TLauncher.jar ]; then
    echo "TLauncher.jar missing"
    exit 1
fi

exec java -jar /usr/share/tlauncher/TLauncher.jar "$@"

